### ISSUE TITLE
sbt has a compilation error when using this plugin

### ISSUE THREAD

**Issue by nayakravi** [lightbend/sbt-google-cloud-storage#4]
The error message is:
No implicit for Append.Value[Seq[sbt.librarymanagement.Resolver], com.lightbend.gcsplugin.GCSResolver] found,
  so com.lightbend.gcsplugin.GCSResolver cannot be appended to Seq[sbt.librarymanagement.Resolver]
      resolvers += GCSResolver.forBucket("bucket_name")

**Comment by olofwalker** [comment]
@nayakravi Could you elaborate on the use case for this ? Normally you would use the plugin by just adding it as a resolver and setting as a publisher
