### ISSUE TITLE
Resolution does not work with sbt-1.3.0/Coursier

### ISSUE THREAD

**Issue by vladimir-lu** [lightbend/sbt-google-cloud-storage#6]
The plugin is not picked up by coursier (because the resolver extends `AbstractRepository` which is an ivy repository)

**Comment by olofwalker** [comment]
Thanks, will look into this.

**Comment by iozozturk** [comment]
Can you publish with the fix if it's a trivial one?

**Comment by jmodrako** [comment]
How can we fix it? I have some spare time right now so I could help but I need some guidance.

**Comment by abdolence** [comment]
I ended up with a completely rewritten plugin for this:

https://github.com/abdolence/sbt-gcs-resolver

**Comment by iozozturk** [comment]
Any people landing here, just forget about using lightbend unmaintained plugins. In GCP now there is Artifact Repo as a service solution, just use it.

**Comment by abdolence** [comment]
> Any people landing here, just forget about using lightbend unmaintained plugins. In GCP now there is Artifact Repo as a service solution, just use it.

Hm, I haven't checked it for a while, but wasn't that required a special maven plugin? Do you work with it in sbt?

**Comment by iozozturk** [comment]
I have been using https://github.com/renaudcerrato/appengine-maven-repository as an alternative for a while. But soon I will switch to Artifact Repo as a service in GCP.  It is maven repo as a service, don't think ou need a special plugin.

**Comment by abdolence** [comment]
>don't think ou need a special plugin.

According to their docs (https://cloud.google.com/artifact-registry/docs/java/quickstart), it still unfortunately does. At least for publishing.

**Comment by iozozturk** [comment]
> > don't think ou need a special plugin.
> 
> According to their docs (https://cloud.google.com/artifact-registry/docs/java/quickstart), it still unfortunately does. At least for publishing.

You are right. I guess my recommendation would be to use https://github.com/renaudcerrato/appengine-maven-repository which you don't need to maintain between sbt releases I guess. Or checkout your implementation as well. 

Perhaps you can also check the plugin for GCP Artifact Repo gradle plugin and if not too much work you can create an sbt plugin too :)

**Comment by abdolence** [comment]
> Perhaps you can also check the plugin for GCP Artifact Repo gradle plugin and if not too much work you can create an sbt plugin too :)

You're reading my thoughts :)

**Comment by abdolence** [comment]
I made some initial implementation support in v1.3.0-SNAPSHOT for GCP Artifacts for Maven repositories, but can't even test it yet, because it isn't available for public usage (still closed alpha) :)

**Comment by abdolence** [comment]
Good news, Google gave me alpha access to Google Artifact registry and I was able to test it and update the plugin implementation and now it works in 1.3.0. 
https://github.com/abdolence/sbt-gcs-resolver

Enjoy!

**Comment by iozozturk** [comment]
Kudos. Looking forward to using it.
